/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequestPatient {
  age?: number;
  email?: string;
  firstName?: string;
  gender?: string;
  lastName?: string;
  password?: string;
  phoneNumber?: string;
}
