/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequestDoctor {
  address?: string;
  city?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  licenseNumber?: string;
  password?: string;
  phoneNumber?: string;
  speciality?: string;
  zipCode?: string;
}
