/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { RegisterRequestDoctor } from './models/register-request-doctor';
export type { RegisterRequestPatient } from './models/register-request-patient';
