/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PatientControllerService } from './services/patient-controller.service';
export { DoctorControllerService } from './services/doctor-controller.service';
export { AdminControllerService } from './services/admin-controller.service';
export { AuthenticationControllerService } from './services/authentication-controller.service';
