/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { delete2 } from '../fn/admin-controller/delete-2';
import { Delete2$Params } from '../fn/admin-controller/delete-2';
import { get2 } from '../fn/admin-controller/get-2';
import { Get2$Params } from '../fn/admin-controller/get-2';
import { post2 } from '../fn/admin-controller/post-2';
import { Post2$Params } from '../fn/admin-controller/post-2';
import { put2 } from '../fn/admin-controller/put-2';
import { Put2$Params } from '../fn/admin-controller/put-2';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `get2()` */
  static readonly Get2Path = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `get2()` instead.
   *
   * This method doesn't expect any request body.
   */
  get2$Response(params?: Get2$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return get2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `get2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  get2(params?: Get2$Params, context?: HttpContext): Observable<string> {
    return this.get2$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `put2()` */
  static readonly Put2Path = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `put2()` instead.
   *
   * This method doesn't expect any request body.
   */
  put2$Response(params?: Put2$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return put2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `put2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  put2(params?: Put2$Params, context?: HttpContext): Observable<string> {
    return this.put2$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `post2()` */
  static readonly Post2Path = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `post2()` instead.
   *
   * This method doesn't expect any request body.
   */
  post2$Response(params?: Post2$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return post2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `post2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  post2(params?: Post2$Params, context?: HttpContext): Observable<string> {
    return this.post2$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `delete2()` */
  static readonly Delete2Path = '/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete2()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2$Response(params?: Delete2$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return delete2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete2$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete2(params?: Delete2$Params, context?: HttpContext): Observable<string> {
    return this.delete2$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
